# Generated by Django 3.1.1 on 2020-09-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proverbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proverb',
            name='category',
            field=models.CharField(choices=[('SYNONYMOUS', 'SYNONYMOUS'), ('ANTITHETICAL', 'ANTITHETICAL'), ('SYNTHETIC', 'SYNTHETIC'), ('INTEGRAL', 'INTEGRAL'), ('PARABOLIC', 'PARABOLIC'), ('COMPARATIVE', 'COMPARATIVE'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
