# Generated by Django 3.1.1 on 2020-09-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proverbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnic',
            name='proverb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethnic', to='Proverbs.proverb'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='proverb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpretation', to='Proverbs.proverb'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='proverb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation', to='Proverbs.proverb'),
        ),
    ]
